### Etapa 3 - EDA Storytteling e Visualização

In [16]:
import pandas as pd
import re

In [17]:
dataframe_final_candidatos = pd.read_csv('dataframe_final_candidatos.csv')

In [18]:
dataframe_final_candidatos.head()

,Data_Hora,IdTweet,Tweet,Candidato
0,2022-07-30 21:56:23+00:00,1553499774732599312,@LulaOficial Sabemos o que fez no verão passad...,Lula
1,2022-07-30 21:56:23+00:00,1553499773126180865,@LuisDerieul Mentiroso. Lula tá aqui no Ceará ...,Lula
2,2022-07-30 21:56:22+00:00,1553499770773245952,@senadorhumberto @LulaOficial Só se vê grama.....,Lula
3,2022-07-30 21:56:22+00:00,1553499770378928134,"@SF_Moro Tu tá com o Lula Marreco, para de show!",Lula
4,2022-07-30 21:56:21+00:00,1553499766763536384,@LulaOficial @ricardostuckert Duvido que tenha...,Lula

In [19]:
dataframe_final_candidatos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Data_Hora  153 non-null    object
 1   IdTweet    153 non-null    int64
 2   Tweet      153 non-null    object
 3   Candidato  153 non-null    object
dtypes: int64(1), object(3)
memory usage: 4.9+ KB

In [20]:
dataframe_final_candidatos.isnull().sum()

Data_Hora    0
IdTweet      0
Tweet        0
Candidato    0
dtype: int64

In [21]:
dataframe_final_candidatos['tweet_limpo'] = dataframe_final_candidatos['Tweet']

In [22]:
dataframe_final_candidatos.head()

,Data_Hora,IdTweet,Tweet,Candidato,tweet_limpo
0,2022-07-30 21:56:23+00:00,1553499774732599312,@LulaOficial Sabemos o que fez no verão passad...,Lula,@LulaOficial Sabemos o que fez no verão passad...
1,2022-07-30 21:56:23+00:00,1553499773126180865,@LuisDerieul Mentiroso. Lula tá aqui no Ceará ...,Lula,@LuisDerieul Mentiroso. Lula tá aqui no Ceará ...
2,2022-07-30 21:56:22+00:00,1553499770773245952,@senadorhumberto @LulaOficial Só se vê grama.....,Lula,@senadorhumberto @LulaOficial Só se vê grama.....
3,2022-07-30 21:56:22+00:00,1553499770378928134,"@SF_Moro Tu tá com o Lula Marreco, para de show!",Lula,"@SF_Moro Tu tá com o Lula Marreco, para de show!"
4,2022-07-30 21:56:21+00:00,1553499766763536384,@LulaOficial @ricardostuckert Duvido que tenha...,Lula,@LulaOficial @ricardostuckert Duvido que tenha...

In [23]:
def limpeza_de_texto(tweet):
  tweet = tweet.lower()
  tweet = re.sub('\n', '', tweet)
  tweet = re.sub('@[^\s]+', '', tweet)
  tweet = re.sub('\B#\S+', '', tweet)
  tweet = re.sub('https?://\S+|www\.\S+', '', tweet)
  return tweet

In [24]:
dataframe_final_candidatos['tweet_limpo'] = dataframe_final_candidatos['Tweet'].apply(lambda i:limpeza_de_texto(i))

In [25]:
dataframe_final_candidatos.head()

,Data_Hora,IdTweet,Tweet,Candidato,tweet_limpo
0,2022-07-30 21:56:23+00:00,1553499774732599312,@LulaOficial Sabemos o que fez no verão passad...,Lula,sabemos o que fez no verão passado.
1,2022-07-30 21:56:23+00:00,1553499773126180865,@LuisDerieul Mentiroso. Lula tá aqui no Ceará ...,Lula,mentiroso. lula tá aqui no ceará hoje o lança...
2,2022-07-30 21:56:22+00:00,1553499770773245952,@senadorhumberto @LulaOficial Só se vê grama.....,Lula,só se vê grama...até os jumentos se evadiram...
3,2022-07-30 21:56:22+00:00,1553499770378928134,"@SF_Moro Tu tá com o Lula Marreco, para de show!",Lula,"tu tá com o lula marreco, para de show!"
4,2022-07-30 21:56:21+00:00,1553499766763536384,@LulaOficial @ricardostuckert Duvido que tenha...,Lula,duvido que tenham ido de graça...

In [26]:
dataframe_final_candidatos.to_csv('dataframe_final_candidatos_pronto_para_sentimentos.csv', sep=',', index=False)